CREATE TABLE IF NOT EXISTS players (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  elo INT NOT NULL DEFAULT 1200,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS matches (
  id SERIAL PRIMARY KEY,
  played_on DATE NOT NULL,
  player_a_id INT NOT NULL REFERENCES players(id),
  player_b_id INT NOT NULL REFERENCES players(id),
  sets JSONB NOT NULL,
  winner_id INT NOT NULL REFERENCES players(id),
  player_a_elo_after INT NOT NULL,
  player_b_elo_after INT NOT NULL,
  notes VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
